#include "lang.h"

const LangTexts LANG_ES = {
    "\nSistema de registro de O/I de equipos\n",
    "\nSeleccione una opcion:\n",
    "\t[1] Entrada\n",
    "\t[2] Salida\n",
    "\t[3] Buscar codigo\n",
    "\t[4] Salir\n",
    "\t[5] Listar registros\n",
    "\t[6] Exportar CSV\n",
    "\t[7] Resumen y salir\n",
    "\nOpcion invalida, intente nuevamente.\n",
    "\nAun no existen equipos registrados...",
    "\nEquipo se encuentra en la base de datos:\n\n",
    "Introduzca el serial del equipo (Sea cuidadoso):\n ",
    "Introduzca el nombre de la persona responsable:\n ",
    "Introduzca la cedula de la persona responsable:\n ",
    "\nNo existe ningun equipo con el serial %s",
    "\nEste dato es obligatorio. Intente nuevamente.\n",
    "\nDesea sobrescribir el serial existente? (S/N) ",
    "\nArchivo de datos: %s\n",
    "\nExportado a %s\n",
    "\nResumen -> Total: %d, Dentro: %d, Fuera: %d\n",
    "Ruta de exportacion (enter para usar pcs.csv): ",
    "\nDesea registrar otra salida? (S/N) ",
    "\nDesea agregar otra entrada? (S/N) ",
    "\nDesea buscar otro equipo? (S/N) ",
    "\nDesea exportar otro archivo? (S/N) ",
    'S',
    'N',
    "Cedula\tNombre\tSerial\tSalio\n",
    "\nListado de registros:\n",
    "\tRegistrada entrada para el equipo con serial: %s \n",
    "\tRegistrada salida para el equipo con serial: %s \n",
    "\tEste equipo ya debio haber entrado, verifique el serial %s\n",
    "\tEste equipo ya debio haber salido, verifique el serial %s\n",
    "Error renombrando el archivo."
};

const LangTexts LANG_EN = {
    "\nEquipment Check-in/Out System\n",
    "\nSelect an option:\n",
    "\t[1] Check-in\n",
    "\t[2] Check-out\n",
    "\t[3] Search serial\n",
    "\t[4] Exit\n",
    "\t[5] List records\n",
    "\t[6] Export CSV\n",
    "\t[7] Summary and exit\n",
    "\nInvalid option, try again.\n",
    "\nNo equipment registered yet...",
    "\nEquipment found in database:\n\n",
    "Enter equipment serial (be careful):\n ",
    "Enter responsible person's name:\n ",
    "Enter responsible person's ID:\n ",
    "\nNo equipment found with serial %s",
    "\nThis field is required. Try again.\n",
    "\nOverwrite existing serial? (Y/N) ",
    "\nData file: %s\n",
    "\nExported to %s\n",
    "\nSummary -> Total: %d, In: %d, Out: %d\n",
    "Export path (press enter for pcs.csv): ",
    "\nAdd another check-in? (Y/N) ",
    "\nRegister another check-out? (Y/N) ",
    "\nSearch another equipment? (Y/N) ",
    "\nExport another file? (Y/N) ",
    'Y',
    'N',
    "ID\tName\tSerial\tOut\n",
    "\nRecord list:\n",
    "\tCheck-in saved for serial: %s \n",
    "\tCheck-out saved for serial: %s \n",
    "\tThis equipment was already checked in, verify serial %s\n",
    "\tThis equipment was already checked out, verify serial %s\n",
    "Error renaming file."
};
