#define SYSTEM_NAME "\nSistema de registro de O/I de equipos\n"
#define CHOICE "\nSeleccione una opcion:\n"
#define CHOICE1 "\t[1] Entrada\n"
#define CHOICE2 "\t[2] Salida\n"
#define CHOICE3 "\t[3] Buscar codigo\n"
#define CHOICE4 "\t[4] Salir\n"
#define NORECORDS "\nAun no existen equipos registrados..."
#define YESRECORD "\nEquipo se encuentra en la base de datos:\n\n"
#define IN_SERIAL "Introduzca el serial del equipo (Sea cuidadoso):\n "
#define IN_PERSON "Introduzca el nombre de la persona responsable:\n "
#define IN_IDENTI "Introduzca la cedula de la persona responsable:\n "
#define NOSERIAL "\nNo existe ningun equipo con el serial %s"
#define ANOTHER_CHECKOUT "\nDesea agregar otra entrada? (S/N) "
#define ANOTHER_CHECKIN "\nDesea registrar otra salida? (S/N) "
#define ANOTHER_SEARCH "\nDesea buscar otro equipo? (S/N) "
#define YES_KEY 'S'
#define NO_KEY 'N'
#define COLUMNS "Cedula\tNombre\tSerial\tSalio\n"
#define CHECKIN_SAVED "\tRegistrada entrada para el equipo con serial: %s \n"
#define CHECKOUT_SAVED "\tRegistrada salida para el equipo con serial: %s \n"
#define ALREADY_CHECKIN "\tEste equipo ya debio haber entrado, verifique el serial %s\n"
#define ALREADY_CHECKOUT "\tEste equipo ya debio haber salido, verifique el serial %s\n"
#define ERROR_RENAME "Error renombrando el archivo."
